export const site = {
  navigation: [{ label: '关于我', href: '#about' }, { label: '教育背景', href: '#education' }, { label: '实习经历', href: '#internship' }, { label: '项目展示', href: '#projects' }, { label: '生活记录', href: '#moments' }, { label: '兴趣爱好', href: '#hobbies' }, { label: '联系我', href: '#contact' }],
  hero: { tagline: 'A little maker, a lot curious.', intro: '我喜欢把模糊的想法拆成小块，再让它们真的跑起来。最近在做 AI Agent、知识检索和本地开发工具。' },
  about: '我是 Sylvia。这里记录我在代码、Agent 和日常创作之间来回穿梭的痕迹。比起给自己贴标签，我更愿意持续做些有趣、可靠，也有一点点个性的东西。',
  stack: ['Python', 'MCP', 'Agentic RAG', 'TypeScript', 'Docker', 'Local-first'],
  links: { github: 'https://github.com/Sylvia145', email: 'bupt_liuxinyi@163.com' },
  photography: [
    { src: '/photography/photo-01.webp', alt: 'Sylvia 的摄影作品 01' },
    { src: '/photography/photo-02.webp', alt: 'Sylvia 的摄影作品 02' },
    { src: '/photography/photo-03.webp', alt: 'Sylvia 的摄影作品 03' },
    { src: '/photography/photo-04.webp', alt: 'Sylvia 的摄影作品 04' },
    { src: '/photography/photo-05.webp', alt: 'Sylvia 的摄影作品 05' },
    { src: '/photography/photo-06.webp', alt: 'Sylvia 的摄影作品 06' },
    { src: '/photography/photo-07.webp', alt: 'Sylvia 的摄影作品 07' },
    { src: '/photography/photo-08.webp', alt: 'Sylvia 的摄影作品 08' },
    { src: '/photography/photo-09.webp', alt: 'Sylvia 的摄影作品 09' },
    { src: '/photography/photo-10.webp', alt: 'Sylvia 的摄影作品 10' },
    { src: '/photography/photo-11.webp', alt: 'Sylvia 的摄影作品 11' },
    { src: '/photography/photo-12.webp', alt: 'Sylvia 的摄影作品 12' },
    { src: '/photography/photo-13.webp', alt: 'Sylvia 的摄影作品 13' },
  ],
  projects: [
    {
      title: 'LiveGraphRAG', subtitle: 'Version-aware knowledge, with proof',
      description: '为版本敏感的私有化软件支持场景构建的 GraphRAG 服务：每一次回答都先经过版本边界、检索证据与引用校验。',
      highlights: ['多版本与 tenant / snapshot 边界，避免旧资料混入当前答案', '关键词、向量、全文与图关系协同检索，保留可点击来源', '引用不足时拒答；异步索引、缓存和观测组件模拟真实运行链路'],
      tags: ['Python', 'FastAPI', 'GraphRAG', 'Neo4j', 'Redis', 'Docker'], href: 'https://github.com/Sylvia145/LiveGraphRAG',
      previewSlides: [
        { src: '/livegraphrag/overview.png?v=2', label: 'PRODUCT OVERVIEW', caption: '版本敏感知识的可验证检索入口', alt: 'LiveGraphRAG 产品首页，展示可追溯的运维知识助手定位' },
        { src: '/livegraphrag/query.png?v=2', label: 'ASK A QUESTION', caption: '选择产品版本后，开始分析具体问题', alt: 'LiveGraphRAG 问题输入与版本选择界面' },
        { src: '/livegraphrag/result.png?v=2', label: 'VERIFIED ANSWER', caption: '答案、推理路径与引用证据同步呈现', alt: 'LiveGraphRAG 可验证答案和分析上下文界面' },
        { src: '/livegraphrag/sources.png?v=2', label: 'SOURCE LIBRARY', caption: '每一段结论都能回到原始资料', alt: 'LiveGraphRAG 回答依据与资料来源列表界面' },
      ],
    },
    {
      title: 'Moka', subtitle: 'A local coding agent with memory',
      description: '一个运行在本地仓库上下文里的终端 coding agent，把模型调用、工具边界、运行证据和长期记忆收进同一个可观察 runtime。',
      highlights: ['TUI / REPL / one-shot 三种入口，共享一套 runtime 与上下文组装', '文件、搜索、Shell、patch 与子 agent 统一纳入工具协议和权限边界', 'session、run evidence、working memory 与 durable topics 让任务可以续接和复盘'],
      tags: ['Python', 'TUI', 'LLM Runtime', 'Memory', 'MCP'], href: 'https://github.com/Sylvia145/moka',
      previewSlides: [
        { src: '/moka/intro.png', label: 'START A SESSION', caption: '本地 TUI、模型与审批状态从这里开始', alt: 'Moka 本地 coding agent 的启动界面' },
        { src: '/moka/tools.png', label: 'RUN WITH TOOLS', caption: '工具调用与运行证据留在同一个会话里', alt: 'Moka 调用工具检查项目结构的界面' },
        { src: '/moka/memory.png', label: 'DURABLE MEMORY', caption: '把项目约定和有效上下文带到下一次任务', alt: 'Moka 展示 durable memory 的界面' },
        { src: '/moka/commands.png', label: 'COMMANDS & SKILLS', caption: '可复用命令和工作流在终端内直接运行', alt: 'Moka 命令和 skills 帮助界面' },
        { src: '/moka/repl.png', label: 'INTERACTIVE REPL', caption: '在本地上下文中持续推进 coding 任务', alt: 'Moka 交互式 REPL 界面' },
      ],
    },
  ],
  contactCopy: '目前正在寻找合适的机会，欢迎联系我~',
} as const
