export const site = {
  navigation: [{ label: '关于我', href: '#about' }, { label: '教育背景', href: '#education' }, { label: '实习经历', href: '#internship' }, { label: '项目展示', href: '#projects' }, { label: '学术成果', href: '#research' }, { label: '竞赛荣誉', href: '#awards' }, { label: '校园工作', href: '#campus' }, { label: '生活记录', href: '#moments' }, { label: '兴趣爱好', href: '#hobbies' }, { label: '联系我', href: '#contact' }],
  hero: { tagline: 'A little maker, a lot curious.', intro: '我喜欢把模糊的想法拆成小块，再让它们真的跑起来。最近在做 AI Agent、知识检索和本地开发工具。' },
  about: '我是 Sylvia。这里记录我在代码、Agent 和日常创作之间来回穿梭的痕迹。比起给自己贴标签，我更愿意持续做些有趣、可靠，也有一点点个性的东西。',
  stack: ['Python', 'MCP', 'Agentic RAG', 'TypeScript', 'Docker', 'Local-first'],
  links: { github: 'https://github.com/Sylvia145', email: 'bupt_liuxinyi@163.com' },
  photography: [
    { src: '/photography/photo-01.webp?v=2', alt: 'Sylvia 的摄影作品 01' },
    { src: '/photography/photo-02.webp?v=3', alt: 'Sylvia 的摄影作品 02' },
    { src: '/photography/photo-03.webp?v=2', alt: 'Sylvia 的摄影作品 03' },
    { src: '/photography/photo-04.webp?v=2', alt: 'Sylvia 的摄影作品 04' },
    { src: '/photography/photo-05.webp?v=2', alt: 'Sylvia 的摄影作品 05' },
    { src: '/photography/photo-06.webp?v=2', alt: 'Sylvia 的摄影作品 06' },
    { src: '/photography/photo-07.webp?v=2', alt: 'Sylvia 的摄影作品 07' },
    { src: '/photography/photo-08.webp?v=2', alt: 'Sylvia 的摄影作品 08' },
    { src: '/photography/photo-09.webp?v=2', alt: 'Sylvia 的摄影作品 09' },
    { src: '/photography/photo-10.webp?v=2', alt: 'Sylvia 的摄影作品 10' },
    { src: '/photography/photo-11.webp?v=2', alt: 'Sylvia 的摄影作品 11' },
    { src: '/photography/photo-12.webp?v=2', alt: 'Sylvia 的摄影作品 12' },
    { src: '/photography/photo-13.webp?v=2', alt: 'Sylvia 的摄影作品 13' },
  ],
  projects: [
    {
      title: 'LiveGraphRAG', subtitle: '版本敏感的 Agentic GraphRAG 知识服务',
      description: '面向 Nextcloud 31—33 多版本技术文档中的版本混用与跨文档证据不足问题，构建以版本化混合检索为默认路径、按需升级受控 Agent 进行图扩展的知识服务，并形成可复现评测闭环。',
      highlights: ['父子分块结合 PostgreSQL FTS、BGE-M3 双路召回与 RRF 融合；冻结题集 Recall@5 从 0.51 提升至 0.76，Cross-Encoder 重排后达 0.95。', '检索优先、按需图扩展；以版本过滤、不可变快照与引用校验隔离证据，双来源问题 Recall@5 从 0.18 提升至 0.63。', '进程内 + Redis 二级缓存配合请求合并；100 个同键并发请求将后端调用从 100 次降至 1 次，P99 延迟降低 40.53%。', '构建本地分层评测闭环，Hit@5 / Hit@10 达 90% / 95%，引用真实性与正确拒答率均为 100%。'],
      tags: ['Python', 'FastAPI', 'PostgreSQL + pgvector', 'Redis', 'Neo4j'], href: 'https://github.com/Sylvia145/LiveGraphRAG',
      previewSlides: [
        { src: '/livegraphrag/overview.png?v=2', label: 'PRODUCT OVERVIEW', caption: '版本敏感知识的可验证检索入口', alt: 'LiveGraphRAG 产品首页，展示可追溯的运维知识助手定位' },
        { src: '/livegraphrag/query.png?v=2', label: 'ASK A QUESTION', caption: '选择产品版本后，开始分析具体问题', alt: 'LiveGraphRAG 问题输入与版本选择界面' },
        { src: '/livegraphrag/result.png?v=2', label: 'VERIFIED ANSWER', caption: '答案、推理路径与引用证据同步呈现', alt: 'LiveGraphRAG 可验证答案和分析上下文界面' },
        { src: '/livegraphrag/sources.png?v=2', label: 'SOURCE LIBRARY', caption: '每一段结论都能回到原始资料', alt: 'LiveGraphRAG 回答依据与资料来源列表界面' },
      ],
    },
    {
      title: 'Moka', subtitle: '面向可审计研发交付的 Coding Agent Runtime',
      description: '针对 CLI Coding Agent 在多轮协作中缺少审计与跨会话记忆的问题，构建将工具调用、代码变更、验证证据与人工审核串联为可追溯链路的 Agent Runtime，补齐从“能执行”到“可复核、可治理、可回归”的闭环。',
      highlights: ['统一工具执行、权限策略校验、任务状态持久化、运行轨迹与交付报告；5 类真实模型测试场景、62 项验收标准全部通过。', '设计 L0—L4 分层记忆，让经验与会话、运行、文件锚点绑定；14 个本地治理场景的证据覆盖与越权拦截率均为 100%。', '统一 stdio 与 Streamable HTTP 远程工具；定义“结果未知”语义并默认停止重试，借助幂等键有限重试，4 类故障均默认仅调用 1 次。', '构建确定性评测：12 个固定任务全部通过；5 个长会话的输入 token 估算中位降幅为 62.28%，独立验证器 5/5 无回归。'],
      tags: ['Python', 'LLM Agent', 'MCP', 'Streamable HTTP', 'Memory', 'Agent Eval'], href: 'https://github.com/Sylvia145/moka',
      previewSlides: [
        { src: '/moka/intro.png', label: 'START A SESSION', caption: '本地 TUI、模型与审批状态从这里开始', alt: 'Moka 本地 coding agent 的启动界面' },
        { src: '/moka/tools.png', label: 'RUN WITH TOOLS', caption: '工具调用与运行证据留在同一个会话里', alt: 'Moka 调用工具检查项目结构的界面' },
        { src: '/moka/memory.png', label: 'DURABLE MEMORY', caption: '把项目约定和有效上下文带到下一次任务', alt: 'Moka 展示 durable memory 的界面' },
        { src: '/moka/commands.png', label: 'COMMANDS & SKILLS', caption: '可复用命令和工作流在终端内直接运行', alt: 'Moka 命令和 skills 帮助界面' },
        { src: '/moka/repl.png', label: 'INTERACTIVE REPL', caption: '在本地上下文中持续推进 coding 任务', alt: 'Moka 交互式 REPL 界面' },
      ],
    },
  ],
  researchOutputs: [
    {
      kind: '论文',
      venue: 'EI · Optical Fiber Communications Conference（光通信顶会）',
      date: '2025.04.04',
      title: 'GSNR-aware Transmission Optimization in Dynamic Programmable Raman Amplifier-enabled Multi-band Optical Systems',
      summary: '面向动态多波段光传输场景，构建 GSNR 感知模型并优化拉曼泵浦功率，让传输容量在变化中保持稳定。',
      metrics: ['RMSE 0.58 dB', 'GSNR 均值 +1.08 dB', '平坦度 +40.02%'],
      details: '针对传统拉曼放大器模型仅适配特定信号、难以优化动态场景传输容量的问题，提出 GSNR 感知的 ANN 模型及传输优化方法。模型扩展 GSNR 输入维度，利用相邻信道相似性降维，并结合 PSO 算法优化拉曼泵浦功率，实现输出 GSNR 的最大化与平坦化。实验显示模型预测 RMSE 为 0.58 dB；在动态传输场景中，相较传统方法，GSNR 均值提升 1.08 dB、平坦度提升 40.02%。',
      href: 'https://ieeexplore.ieee.org/abstract/document/11046908',
      image: '/research/paper-cover.webp',
      thumbnail: '/research/paper-cover-thumb.webp',
      placeholder: '论文成果图 / 待补充',
    },
    {
      kind: '授权专利',
      venue: 'CN120128266B',
      date: '2025.11.13',
      title: '一种基于 GSNR 感知的动态多波段光网络传输容量优化方法',
      summary: '将 GSNR 分布引入数据驱动模型，以动态自适应与闭环反馈提升多波段光网络的传输容量。',
      metrics: ['GSNR 感知', '动态自适应', '闭环反馈'],
      details: '本专利提出基于 GSNR 感知的动态多波段光网络传输容量优化方法，将输入信号的 GSNR 分布纳入数据驱动模型输入维度；结合信道特征降维构建人工神经网络感知模型，并搭配优化算法与闭环反馈控制系统，实现拉曼放大器泵浦参数的动态自适应调整，改善传统方法在动态场景中泛化性不足的问题。',
      href: 'https://kns.cnki.net/kcms2/article/abstract?v=14XpHnsxtHHEDsWZVRSv2_6wZ5q7WF_ZmIApwNC6q-PbTQtJvQ_lLrQEfqjUnuMaRKo3GcbB-RdMWf4NCgFfMB6t0hFnRxYF4P6nTER1SrIVkzAGaOSv2hqpIw5ms0bNJh6OFRLCj4oLVNs6QHhY3BzOpmh35TFeTi-BN9Oyc9T1UYo73mdxLg==&uniplatform=NZKPT&language=CHS',
      image: '/research/patent-cover.webp',
      thumbnail: '/research/patent-cover-thumb.webp',
      placeholder: '专利成果图 / 待补充',
    },
  ],
  competitions: [
    { date: '2023.06', title: '“大唐杯”全国大学生新一代信息通信技术大赛', level: '国家级三等奖', featured: true },
    { date: '2022.10', title: '高教社杯全国大学生数学建模竞赛', level: '北京市二等奖' },
    { date: '2023.05', title: '美国大学生数学建模竞赛', level: 'Honorable Mention' },
    { date: '2023.05', title: '中国大学生计算机设计大赛', level: '北京市三等奖' },
    { date: '2023.03', title: '北京科技大学第十六届智能车竞赛', level: '一等奖（冠军）' },
  ],
  honors: [
    { date: '2021.05', title: '人民（新生）一等奖学金', level: '前 2%' },
    { date: '2021–2023', title: '人民一等奖学金', level: '前 4%' },
    { date: '2021.11', title: '优秀三好学生', level: '校级荣誉' },
    { date: '2022.11', title: '优秀学生干部', level: '校级荣誉' },
    { date: '2024.06', title: '北京市优秀毕业生', level: '市级荣誉' },
    { date: '2025.09', title: '研究生学业一等奖学金', level: '一等奖学金' },
  ],
  campusActivities: [
    {
      date: '2021.07 — 2021.08',
      role: '北京科技大学拾忆潇湘社会实践队队长',
      highlights: ['院级第 3'],
      summary: '带领队员深入了解湖南党史，通过采访、问卷与实地寻访调研党史教育、宣传与学习现状，并借助公众平台进行党史宣传，最终带领实践团取得院级第 3 的成绩。',
      featured: true,
    },
    {
      date: '2021.03 — 2022.09',
      role: '北京科技大学计算机与通信工程学院学风部部长',
      highlights: ['学生工作'],
      summary: '制作活动推送与串讲通知，宣传学风建设相关活动，并为先进班集体、优秀党支部答辩、特奖答辩等大型活动提供支持。',
    },
    {
      date: '2021.03 — 2021.06',
      role: '北京科技大学计算机与通信工程学院朋辈讲师团讲师',
      highlights: ['银牌讲师', '模拟授课大赛三等奖'],
      summary: '开展高等数学、线性代数等课程串讲，帮助同学梳理知识点；获“银牌讲师”称号及模拟授课大赛三等奖。',
    },
  ],
  contactCopy: '目前正在寻找合适的机会，欢迎联系我~',
} as const
